server:
  port: 8080

spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: 'http://localhost:8091'
          predicates:
            - Path=/api/v1/students/**
        - id: courses
          uri: 'http://localhost:8092'
          predicates:
            - Path=/api/v1/courses/**