server:
  port: 8091
  
spring:
  application:
    name: microservice-student
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=db_students;trustServerCertificate=true
    username: sa
    password: Server2023*
    
  jpa:
    hibernate:
      ddl-auto: update
    database: sql-server
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format-sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      